---
- hosts: "url_shortener"
  become: "yes"
  roles:
    - "City-of-Bloomington.php"
    - "City-of-Bloomington.mysql"

  tasks:
    - name: "Install php and related packages"
      apt:
        name: "{{ packages }}"
        state: "present"
      vars:
        packages:
        - 'imagemagick'
        - "php-mysql"
        - 'php-imagick'

    - name: "Create mysql database"
      mysql_db:
        config_file: "{{ mysql_defaults_extra_file }}"
        name: "{{ url_shortener_db.default.name }}"
        state: "present"
      no_log: "True"

    - name: "Create mysql user for site"
      mysql_user:
        name:     "{{ url_shortener_db.default.user }}"
        password: "{{ url_shortener_db.default.pass }}"
        priv:     "{{ url_shortener_db.default.name }}.*:ALL"
        state: "present"
        config_file: "{{ mysql_defaults_extra_file }}"
      no_log: "True"

    - name: "Create directories"
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
        mode:  "u=rwX,g=rwXs,o=rX"
      with_items:
        - "{{ url_shortener_install_path }}"
        - "{{ url_shortener_backup_path  }}"
        - "{{ url_shortener_site_home    }}"
        - "{{ url_shortener_site_home    }}/sessions"
        - "{{ url_shortener_site_home    }}/qrcodes"
        - "/var/log/cron"

    - name: "Extract release"
      ansible.builtin.unarchive:
        src:  "{{ url_shortener_archive_path }}"
        dest: "{{ url_shortener_install_path }}"
        owner: 'www-data'
        group: 'staff'

    - name: "Apache configuration"
      template:
        src:  "apache.conf"
        dest: "/etc/apache2/sites-enabled/conf.d/url_shortener.conf"
      notify: "apache_restart"

    - name: "Install CRON"
      template:
        src:  "cron.sh"
        dest: "/etc/cron.daily/backup.d/url_shortener"
        mode: "0755"

    - name: "Install site_config"
      template:
        src:  "site_config.j2"
        dest: "{{ url_shortener_site_home }}/site_config.php"

    - name: 'Update directory permissions'
      ansible.builtin.file:
        path: "{{ item }}"
        recurse: 'yes'
        mode:  'u=rwX,g=rwX,o=rX'
        owner: 'www-data'
        group: 'staff'
      with_items:
        - "{{ url_shortener_install_path }}"
        - "{{ url_shortener_backup_path  }}"
        - "{{ url_shortener_site_home    }}"
...
